Add content for Nodes, Workloads, Dashboard and Security Events
neuvector/docs pull request #109
Opened 2024-08-22 05:30 UTC by xingzhang-suse

2024-10-14 12:10 UTC, nunix commented
@xingzhang-suse can I kindly ask you to add the `.idea` to your `.gitignore` file that should be located at the root of the repo.

2024-10-14 17:08 UTC, xingzhang-suse commented
> @xingzhang-suse can I kindly ask you to add the `.idea` to your `.gitignore` file that should be located at the root of the repo.

Sure, I have removed .idea folder from code and add it into .gitignore.

2024-11-09 00:40 UTC, sunilarjun requested changes
Hello! I've made some edits with adjusting grammar, once fixed this PR should be good to merge in. Thank you!

2024-11-09 00:40 UTC, sunilarjun commented on docs/06.scanning/01.scanning/01.vulnerabilities/01.vulnerabilities.md
> +Selecting any CVE listed provides additional details about the CVE, remediation, and which images, nodes, or containers are Impacted. The Protection State icon (circle) shows various colors to indica
```suggestion
Selecting any CVE listed provides additional details about the CVE, remediation, and which images, nodes, or containers are Impacted. The Protection State icon (circle) shows various colors to indicate a rough percentage of the impacted items which are unprotected by NeuVector during run-time, protected by NeuVector rules (in a Monitor or Protect mode), or unaffected in run-time (e.g. an image scanned with this vulnerability has no running containers). Images include the registry's static images and the run-time container's images. The run-time container's images have the same colors as their containers. The Protection State column color scheme is:
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/06.scanning/02.registry/02.registry.md
> +From v5.4.0 NeuVector provide "View all scanned images". Users don't have to look into registry to see a specific image. Instead, users can click the last row to get all scanned image list in one sto
```suggestion
From v5.4.0 NeuVector provides a "View all scanned images" option. Users don't have to look into a registry to see a specific image. Instead, users can click the last row to list all scanned images.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/06.scanning/02.registry/02.registry.md
> +Users can also land to Registries page and open specific image from the hyperlink from Containers page. If the image name is not clickable, it means that the image has not been scanned yet.
```suggestion
Users can also land on the Registries page and open specific images from the hyperlink from the Containers page. If the image name is not clickable, it means that the image has not been scanned yet.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +### Monitor overview of security status
```suggestion
### Monitor Overview of Security Status
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +In UI Extension on Rancher portal, NeuVector's Dashboard works similar as its standalone page. It provides security risk score and factors to let user know the security status of the clusters. In the
```suggestion
In the UI Extension in the Rancher portal, NeuVector's Dashboard works similar as its standalone page. It provides security risk score factors to let users know the security status of their clusters. In the bottom panel, it provides 4 tabs to let users switch the charts to monitor different categories.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +In Security Events tab, the line chart shows a date-based event count in a timeline.
```suggestion
In the Security Events tab, the line chart shows a date-based event count in a timeline.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +In Ingress and Egress Exposure tab, the stacked bar chart shows amount of exposed endpoints by actions.
```suggestion
In Ingress and Egress Exposure tab, the stacked bar chart shows the amount of exposed endpoints by actions.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +On the right side, the exposure tables show egress and ingress endpoint service with scan informations.
```suggestion
On the right side, the exposure tables show egress and ingress endpoint service with scan information.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +Click on the row of egress/ingress table, the table shows conversations on specific service. The FQDN name / IP address is shown with geography location based national flag in External Host field.
```suggestion
Click on the row of egress/ingress table, the table shows conversations on specific services. The FQDN name / IP address is shown with a geography location based national flag in the External Host field.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +Click on the External Host, it redirects to whois.com to show the IP address' detail informations.
```suggestion
Click on the External Host, it redirects to whois.com to show the IP address' detail information.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +In Policy Mode tab, the pie charts shows the ratio and numbers of pods / services under different policy mode.
```suggestion
In the Policy Mode tab, the pie charts show the ratio and numbers of pods / services under different policy modes.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +In Top Vulnerable Assets tab, the bar charts shows the top 5 pods / nodes which contain high or medium severity vulnerabilities.
```suggestion
In the Top Vulnerable Assets tab, the bar charts show the top 5 pods / nodes which contain high or medium severity vulnerabilities.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +### Not included functions comparing with NeuVector standalone page
```suggestion
### Functions Not Included When Comparing with NeuVector Standalone Page
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/02.runtime _security/runtime_security.md
> +As Rancher has its own Nodes and Workloads page to manage and monitor the assets' status, NeuVector injects components to display its runtime scan result.
```suggestion
As Rancher has its own Nodes and Workloads page to manage and monitor the assets statuses, NeuVector injects components to display its runtime scan result.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/02.runtime _security/runtime_security.md
> +In nodes summary table, vulnerabilities column is injected to show each node's detected vulnerabilities amount by high / medium severity.
```suggestion
In the nodes summary table, the vulnerabilities column is injected to show each node's detected vulnerabilities amount by high / medium severity.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/02.runtime _security/runtime_security.md
> +Click on the vulnerabilities cell, a slide panel comes from right side of the page to show scan result details. The database version of the scanner is shown as well as a filterable vulnerability list
```suggestion
Click on the vulnerabilities cell, a slide panel will come from the right side of the page to show scan result details. The database version of the scanner is shown as well as a filterable vulnerability list.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/02.runtime _security/runtime_security.md
> +Click on the node name cell on nodes table, it redirects to node detail page. NeuVector inject a tab to show vulnerability list.
```suggestion
Click on the node name cell on nodes table, it redirects to the node detail page. NeuVector injects a tab to show the vulnerability list.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/02.runtime _security/runtime_security.md
> +A CSV file downloading button is provided above the vulnerabilities table. The file data includes all the fields which are in the table.
```suggestion
A CSV file download button is provided above the vulnerabilities table. The file data includes all the fields which are in the table.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/02.runtime _security/runtime_security.md
> +Temporarily, vulnerabilities column will not be injected in workloads table in v5.4 release due to potential performance concern. NeuVector team will work with Rancher team to deal with it and integr
```suggestion
Temporarily, the vulnerabilities column will not be injected in the workloads table in the v5.4 release due to potential performance concern. The NeuVector team will work with the Rancher team to integrate it soon.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/02.runtime _security/runtime_security.md
> +Click on a pod name on the workloads table, it redirects to pod detail page. NeuVector inject a tab to show vulnerability list.
```suggestion
Click on a pod name in the workloads table, it redirects to the pod detail page. NeuVector injects a tab to show the vulnerability list.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/03.notifictions/notifications.md
> +In UI Extension on Rancher portal, Security Events works similar as NeuVector standalone page.
```suggestion
In the UI Extension on the Rancher portal, Security Events work similar to the NeuVector standalone page.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/03.notifictions/notifications.md
> +The events can be triggered by several factors
```suggestion
The events can be triggered by several factors:
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/03.notifictions/notifications.md
> +Slide left or  / and right dot on the time slider to filter events by date.
```suggestion
Slide the dot left or right on the time slider to filter events by date.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/03.notifictions/notifications.md
> +Type in keyword into quick filter box to filter any event which includes the keyword.
```suggestion
Type in keywords into the quick filter box to filter any event which includes the keyword.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/03.notifictions/notifications.md
> +Open the Advanced filter slide panel, there are multiple options supporting your searching.
```suggestion
Open the Advanced filter slide panel, and you will find multiple options supporting your search:
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/03.notifictions/notifications.md
> +To read the details of the event, click on a record to expand the panel. In the message box, it contains more informations.
```suggestion
To read the details of the event, click on a record to expand the panel. In the message box you can view more information.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/03.notifictions/notifications.md
> +Host name is clickable for opening host detail popup. Vulnerabilities and Group have external link to redirect to NeuVector SSO page.
```suggestion
The Host name is clickable for opening the host detail popup. Vulnerabilities and Group have an external link to redirect to the NeuVector SSO page.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/03.notifictions/notifications.md
> +Workload name is clickable for opening workload detail popup. Group has external link to redirect to NeuVector SSO page.
```suggestion
The Workload name is clickable for opening the workload detail popup. Group has an external link to redirect to the NeuVector SSO page.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/03.notifictions/notifications.md
> +Reported by field in the message box is clickable for opening enforcer detail popup.
```suggestion
The Reported by field in the message box is clickable and opens the enforcer detail popup.
```

2024-11-09 00:40 UTC, sunilarjun commented on docs/15.ui_extension/03.notifictions/notifications.md
> +### Not included functions comparing with NeuVector standalone page
```suggestion
### Functions Not Included When Comparing with NeuVector Standalone Page
```

2024-11-14 01:19 UTC, xingzhang-suse commented on docs/06.scanning/01.scanning/01.vulnerabilities/01.vulnerabilities.md
> +Selecting any CVE listed provides additional details about the CVE, remediation, and which images, nodes, or containers are Impacted. The Protection State icon (circle) shows various colors to indica
Fixed

2024-11-14 01:19 UTC, xingzhang-suse commented on docs/06.scanning/02.registry/02.registry.md
> +Users can also land to Registries page and open specific image from the hyperlink from Containers page. If the image name is not clickable, it means that the image has not been scanned yet.
Fixed

2024-11-14 01:20 UTC, xingzhang-suse commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +### Monitor overview of security status
Fixed

2024-11-14 01:20 UTC, xingzhang-suse commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +In UI Extension on Rancher portal, NeuVector's Dashboard works similar as its standalone page. It provides security risk score and factors to let user know the security status of the clusters. In the
Fixed

2024-11-14 01:27 UTC, xingzhang-suse commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +In Security Events tab, the line chart shows a date-based event count in a timeline.
Fixed

2024-11-14 01:27 UTC, xingzhang-suse commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +In Ingress and Egress Exposure tab, the stacked bar chart shows amount of exposed endpoints by actions.
Fixed

2024-11-14 01:27 UTC, xingzhang-suse commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +On the right side, the exposure tables show egress and ingress endpoint service with scan informations.
Fixed

2024-11-14 01:27 UTC, xingzhang-suse commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +Click on the row of egress/ingress table, the table shows conversations on specific service. The FQDN name / IP address is shown with geography location based national flag in External Host field.
Fixed

2024-11-14 01:28 UTC, xingzhang-suse commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +Click on the External Host, it redirects to whois.com to show the IP address' detail informations.
Fixed

2024-11-14 01:28 UTC, xingzhang-suse commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +In Policy Mode tab, the pie charts shows the ratio and numbers of pods / services under different policy mode.
Fixed

2024-11-14 01:28 UTC, xingzhang-suse commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +In Top Vulnerable Assets tab, the bar charts shows the top 5 pods / nodes which contain high or medium severity vulnerabilities.
Fixed

2024-11-14 01:28 UTC, xingzhang-suse commented on docs/15.ui_extension/01.dashboard/01.dashboard.md
> +### Not included functions comparing with NeuVector standalone page
Fixed

2024-11-14 01:28 UTC, xingzhang-suse commented on docs/15.ui_extension/02.runtime _security/runtime_security.md
> +As Rancher has its own Nodes and Workloads page to manage and monitor the assets' status, NeuVector injects components to display its runtime scan result.
Fixed

2024-11-14 01:28 UTC, xingzhang-suse commented on docs/15.ui_extension/02.runtime _security/runtime_security.md
> +In nodes summary table, vulnerabilities column is injected to show each node's detected vulnerabilities amount by high / medium severity.
Fixed

2024-11-14 01:28 UTC, xingzhang-suse commented on docs/15.ui_extension/02.runtime _security/runtime_security.md
> +Click on the vulnerabilities cell, a slide panel comes from right side of the page to show scan result details. The database version of the scanner is shown as well as a filterable vulnerability list
Fixed

2024-11-14 01:28 UTC, xingzhang-suse commented on docs/15.ui_extension/02.runtime _security/runtime_security.md
> +Click on the node name cell on nodes table, it redirects to node detail page. NeuVector inject a tab to show vulnerability list.
Fixed

2024-11-14 01:28 UTC, xingzhang-suse commented on docs/15.ui_extension/02.runtime _security/runtime_security.md
> +A CSV file downloading button is provided above the vulnerabilities table. The file data includes all the fields which are in the table.
Fixed

2024-11-14 01:28 UTC, xingzhang-suse commented on docs/15.ui_extension/02.runtime _security/runtime_security.md
> +Temporarily, vulnerabilities column will not be injected in workloads table in v5.4 release due to potential performance concern. NeuVector team will work with Rancher team to deal with it and integr
Fixed

2024-11-14 01:28 UTC, xingzhang-suse commented on docs/15.ui_extension/02.runtime _security/runtime_security.md
> +Click on a pod name on the workloads table, it redirects to pod detail page. NeuVector inject a tab to show vulnerability list.
Fixed

2024-11-14 01:28 UTC, xingzhang-suse commented on docs/15.ui_extension/03.notifictions/notifications.md
> +In UI Extension on Rancher portal, Security Events works similar as NeuVector standalone page.
Fixed

2024-11-14 01:28 UTC, xingzhang-suse commented on docs/15.ui_extension/03.notifictions/notifications.md
> +The events can be triggered by several factors
Fixed

2024-11-14 01:28 UTC, xingzhang-suse commented on docs/15.ui_extension/03.notifictions/notifications.md
> +Slide left or  / and right dot on the time slider to filter events by date.
Fixed

2024-11-14 01:28 UTC, xingzhang-suse commented on docs/15.ui_extension/03.notifictions/notifications.md
> +Type in keyword into quick filter box to filter any event which includes the keyword.
Fixed

2024-11-14 01:29 UTC, xingzhang-suse commented on docs/15.ui_extension/03.notifictions/notifications.md
> +Open the Advanced filter slide panel, there are multiple options supporting your searching.
Fixed

2024-11-14 01:29 UTC, xingzhang-suse commented on docs/15.ui_extension/03.notifictions/notifications.md
> +To read the details of the event, click on a record to expand the panel. In the message box, it contains more informations.
Fixed

2024-11-14 01:29 UTC, xingzhang-suse commented on docs/15.ui_extension/03.notifictions/notifications.md
> +Host name is clickable for opening host detail popup. Vulnerabilities and Group have external link to redirect to NeuVector SSO page.
Fixed

2024-11-14 01:29 UTC, xingzhang-suse commented on docs/15.ui_extension/03.notifictions/notifications.md
> +Workload name is clickable for opening workload detail popup. Group has external link to redirect to NeuVector SSO page.
Fixed

2024-11-14 01:29 UTC, xingzhang-suse commented on docs/15.ui_extension/03.notifictions/notifications.md
> +Reported by field in the message box is clickable for opening enforcer detail popup.
Fixed

2024-11-14 01:29 UTC, xingzhang-suse commented on docs/15.ui_extension/03.notifictions/notifications.md
> +### Not included functions comparing with NeuVector standalone page
Fixed

2024-11-20 18:41 UTC, sunilarjun approved these changes
Thank you for addressing the changes!

2024-11-20 18:41 UTC, merged