Documentation update for v5.4.0 scan caching feature.
neuvector/docs pull request #118
Opened 2024-09-27 16:42 UTC by venkateshjayagopal

Documentation update for v5.4.0 scan caching feature.

2024-09-27 17:24 UTC, jayhuang-suse approved these changes

2024-10-08 02:13 UTC, jayhuang-suse approved these changes

2024-10-30 18:26 UTC, sunilarjun requested changes
Hello! Requesting some changes to the title from "Replacing" to "Rotating" and updating the note syntax to the Docusaurus admonition, otherwise looks good. Thank you!

2024-10-30 18:26 UTC, sunilarjun commented on versioned_docs/version-5.4/03.configuration/01.console/03.certrotate/03.certrotate.md
> +title: Replacing Self-Signed Certificate
```suggestion
title: Rotating Self-Signed Certificate
```

2024-10-30 18:26 UTC, sunilarjun commented on versioned_docs/version-5.4/05.policy/03.admission/03.admission.md
> +Kubernetes still pulls image from the default registry server (configured in its runtime configuration) when it's not specified in the YAML. It means when registry server is not specified in the YAML
```suggestion
:::note
Please note, NeuVector doesn't tell Kubernetes about the default registry server when it's not specified in the YAML. NeuVector only uses the configured CTRL_SEARCH_REGISTRIES value for evaluating the admission control requests.
Kubernetes still pulls image from the default registry server (configured in its runtime configuration) when it's not specified in the YAML. It means when registry server is not specified in the YAML, NeuVector & Kubernetes could use different default registry server URLs.
:::
```

2024-10-30 18:26 UTC, sunilarjun commented on versioned_docs/version-5.4/06.scanning/07.scan_caching/scan_caching.md
> +> Note This feature is only supported from v5.4.0 onwards.
```suggestion
:::note
This feature is only supported from v5.4.0 onwards.
:::
```

2024-10-30 18:26 UTC, sunilarjun commented on versioned_docs/version-5.4/06.scanning/07.scan_caching/scan_caching.md
> +> NOTE: Mounting ```/tmp/images/caches``` on PVC is not supported.
```suggestion
:::note
Mounting ```/tmp/images/caches``` on PVC is not supported.
:::
```

2024-10-30 18:31 UTC, venkateshjayagopal commented
Thanks for reviewing the changes. I have accepted your changes.

2024-10-30 18:34 UTC, sunilarjun approved these changes
Thanks for addressing the changes, approved!

2024-10-30 18:34 UTC, merged