updated airgapped instructions to use `hauler`
neuvector/docs pull request #139
Opened 2024-12-05 06:02 UTC by zackbradys

- Updated airgapped instructions to use`hauler`
- Backported instructions for previously versions of `neuvector`/`docs`

2024-12-05 20:48 UTC, zackbradys commented
need to add one more change before approving/merging

2024-12-05 22:18 UTC, jorn-k approved these changes

2024-12-05 22:19 UTC, jorn-k approved these changes
TY!

2024-12-06 02:00 UTC, zackbradys commented
ready for review and approval... pending any feedback!

2024-12-06 02:05 UTC, zackbradys commented
ready for review and approval... pending any feedback!

2025-01-16 16:58 UTC, sunilarjun requested changes
Hello and thank you for posting this content update! Apologies on the review delay, I've just left some comments to address a few minor grammar edits. Additionally, could you please remove the `package-lock.json` and `yarn.lock` file changes if they are unnecessary for this update. Please let me know if you have any questions, thank you.

2025-01-16 16:58 UTC, sunilarjun commented on docs/02.deploying/09.airgap/09.airgap.md
> +### Prerequistes
```suggestion
### Prerequisites
```

2025-01-16 16:58 UTC, sunilarjun commented on versioned_docs/version-5.2/02.deploying/09.airgap/09.airgap.md
> +### Prerequistes
```suggestion
### Prerequisites
```

2025-01-16 16:58 UTC, sunilarjun commented on versioned_docs/version-5.3/02.deploying/09.airgap/09.airgap.md
> +### Prerequistes
```suggestion
### Prerequisites
```

2025-01-16 16:58 UTC, sunilarjun commented on versioned_docs/version-5.4/02.deploying/09.airgap/09.airgap.md
> +### Prerequistes
```suggestion
### Prerequisites
```

2025-01-16 16:58 UTC, sunilarjun commented on versioned_docs/version-5.4/02.deploying/09.airgap/09.airgap.md
> +If you are a **Rancher Prime** or **Rancher Government Carbide** customer, please make sure to use the commands that fetch the all the artifacts from the respective private registry. If you're a supp
```suggestion
If you are a **Rancher Prime** or **Rancher Government Carbide** customer, please make sure to use the commands that fetch all artifacts from the respective private registry. If you're a supported customer and do not know the correct `<registry-url>` for Prime or Carbide, please contact your respective support team!
```

2025-01-16 16:58 UTC, sunilarjun commented on versioned_docs/version-5.4/02.deploying/09.airgap/09.airgap.md
> +In order to get the required container images and helm chart for NeuVector, we are able to utilize `hauler` to easily fetch, package, and distribute all the bits. We can utilize commands or declarati
```suggestion
In order to get the required container images and Helm chart for NeuVector, we are able to utilize `hauler` to easily fetch, package, and distribute all the bits. We can utilize commands or declarative manifests within `hauler` to do this using either method.
```

2025-01-16 16:58 UTC, sunilarjun commented on versioned_docs/version-5.3/02.deploying/09.airgap/09.airgap.md
> +Once you have copied everything to your existing registry or served your own registry, you can install `NeuVector` as normal, with a few modified values to account for the airgapped environment. Plea
```suggestion
Once you have copied everything to your existing registry or served your own registry, you can install `NeuVector` as normal, with a few modified values to account for the airgapped environment. Please note you may need to adjust the below example for your environment.
```

2025-01-16 16:58 UTC, sunilarjun commented on versioned_docs/version-5.3/02.deploying/09.airgap/09.airgap.md
> +In order to get the required container images and helm chart for NeuVector, we are able to utilize `hauler` to easily fetch, package, and distribute all the bits. We can utilize commands or declarati
```suggestion
In order to get the required container images and Helm chart for NeuVector, we are able to utilize `hauler` to easily fetch, package, and distribute all the bits. We can utilize commands or declarative manifests within `hauler` to do this using either method.
```

2025-01-16 16:58 UTC, sunilarjun commented on versioned_docs/version-5.3/02.deploying/09.airgap/09.airgap.md
> +If you are a **Rancher Prime** or **Rancher Government Carbide** customer, please make sure to use the commands that fetch the all the artifacts from the respective private registry. If you're a supp
```suggestion
If you are a **Rancher Prime** or **Rancher Government Carbide** customer, please make sure to use the commands that fetch all artifacts from the respective private registry. If you're a supported customer and do not know the correct `<registry-url>` for Prime or Carbide, please contact your respective support team!
```

2025-01-16 16:58 UTC, sunilarjun commented on versioned_docs/version-5.2/02.deploying/09.airgap/09.airgap.md
> +Once you have copied everything to your existing registry or served your own registry, you can install `NeuVector` as normal, with a few modified values to account for the airgapped environment. Plea
```suggestion
Once you have copied everything to your existing registry or served your own registry, you can install `NeuVector` as normal, with a few modified values to account for the airgapped environment. Please note you may need to adjust the below example for your environment.
```

2025-01-16 16:58 UTC, sunilarjun commented on versioned_docs/version-5.2/02.deploying/09.airgap/09.airgap.md
> +In order to get the required container images and helm chart for NeuVector, we are able to utilize `hauler` to easily fetch, package, and distribute all the bits. We can utilize commands or declarati
```suggestion
In order to get the required container images and Helm chart for NeuVector, we are able to utilize `hauler` to easily fetch, package, and distribute all the bits. We can utilize commands or declarative manifests within `hauler` to do this using either method.
```

2025-01-16 16:58 UTC, sunilarjun commented on versioned_docs/version-5.2/02.deploying/09.airgap/09.airgap.md
> +If you are a **Rancher Prime** or **Rancher Government Carbide** customer, please make sure to use the commands that fetch the all the artifacts from the respective private registry. If you're a supp
```suggestion
If you are a **Rancher Prime** or **Rancher Government Carbide** customer, please make sure to use the commands that fetch all artifacts from the respective private registry. If you're a supported customer and do not know the correct `<registry-url>` for Prime or Carbide, please contact your respective support team!
```

2025-01-16 16:58 UTC, sunilarjun commented on docs/02.deploying/09.airgap/09.airgap.md
> +Once you have copied everything to your existing registry or served your own registry, you can install `NeuVector` as normal, with a few modified values to account for the airgapped environment. Plea
```suggestion
Once you have copied everything to your existing registry or served your own registry, you can install `NeuVector` as normal, with a few modified values to account for the airgapped environment. Please note you may need to adjust the below example for your environment.
```

2025-01-16 16:58 UTC, sunilarjun commented on docs/02.deploying/09.airgap/09.airgap.md
> +If you are a **Rancher Prime** or **Rancher Government Carbide** customer, please make sure to use the commands that fetch the all the artifacts from the respective private registry. If you're a supp
```suggestion
If you are a **Rancher Prime** or **Rancher Government Carbide** customer, please make sure to use the commands that fetch all artifacts from the respective private registry. If you're a supported customer and do not know the correct `<registry-url>` for Prime or Carbide, please contact your respective support team!
```

2025-01-16 16:58 UTC, sunilarjun commented on docs/02.deploying/09.airgap/09.airgap.md
> +In order to get the required container images and helm chart for NeuVector, we are able to utilize `hauler` to easily fetch, package, and distribute all the bits. We can utilize commands or declarati
```suggestion
In order to get the required container images and Helm chart for NeuVector, we are able to utilize `hauler` to easily fetch, package, and distribute all the bits. We can utilize commands or declarative manifests within `hauler` to do this using either method.
```

2025-01-30 19:21 UTC, zackbradys commented
Hey @sunilarjun! Apologies for taking so long to update this. I've updated the PR with all your requested changes! Let me know if you would like to see anything else updated.

2025-01-30 20:14 UTC, sunilarjun approved these changes
Thank you for updating the content! Approved

2025-01-30 20:14 UTC, merged