Create 12.rancher_sso_rbac.md
neuvector/docs pull request #140
Opened 2024-12-09 18:29 UTC by brunoebernardi

Hi Nuno. I'm creating this documentation based on the NVSHAS-9463 case and some experiences I've had with customers in some support cases. I thought it would be interesting to include all these topics and use cases in the documentation, but please feel free to modify it if necessary. Thanks!

2024-12-30 21:36 UTC, sunilarjun requested changes
Thank you for this page addition! I left some review comments on adjusting some phrasing/grammar and also could you please add this page to the versioned_docs v5.4 similar section (versioned_docs/version-5.4/08.integration)? Please let me know if you have any questions or if you need any help with versioning I can assist, thank you!

2024-12-30 21:36 UTC, sunilarjun commented on docs/08.integration/12.rancher_sso_rbac.md
> +Starting with NeuVector 5.4, full compatibility and integration of NeuVector with Rancher RBAC has been included. This will offer the user the possibility of customizing specific permissions based on
```suggestion
Starting with NeuVector 5.4, full compatibility and integration of NeuVector with Rancher RBAC has been included. This offers users the possibility of customizing specific permissions based on the profile of the user or group that should access NeuVector.
```

2024-12-30 21:36 UTC, sunilarjun commented on docs/08.integration/12.rancher_sso_rbac.md
> +In the Rancher console, Users & Authentication -> Role Templates page, customers can create Global, Cluster, Project, and Namespaces roles with specific Neuvector Verbs, Resources, and API Groups. Wh
```suggestion
In the Rancher console, Users & Authentication -> Role Templates page, customers can create Global, Cluster, Project, and Namespace roles with specific Neuvector Verbs, Resources, and API Groups. When such a Rancher role is assigned to a Rancher user, the user's NeuVector SSO session is assigned different NeuVector permissions accordingly. This is to provide SSO users with custom roles (i.e., roles other than the reserved admin/reader/fedAdmin/fedReader roles).
```

2024-12-30 21:36 UTC, sunilarjun commented on docs/08.integration/12.rancher_sso_rbac.md
> +### Supported Custom NeuVector role mapping in Rancher SSO
```suggestion
### Supported Custom NeuVector Role Mapping in Rancher SSO
```

2024-12-30 21:36 UTC, sunilarjun commented on docs/08.integration/12.rancher_sso_rbac.md
> +### Definitions and expectations with Global, Cluster and Project/Namespace roles
```suggestion
### Definitions and Expectations with Global, Cluster, and Project/Namespace Roles 
```

2024-12-30 21:36 UTC, sunilarjun commented on docs/08.integration/12.rancher_sso_rbac.md
> +  + Mapped to NeuVector fedAdmin role on NeuVector fed-master cluster  (It means that the customer cannot map a Rancher Global Role to NeuVector admin role if that NeuVector is a master cluster)
```suggestion
  + Mapped to NeuVector fedAdmin role on NeuVector fed-master cluster  (This means users cannot map a Rancher Global role to a NeuVector admin role if NeuVector is on a master cluster)
```

2024-12-30 21:36 UTC, sunilarjun commented on docs/08.integration/12.rancher_sso_rbac.md
> +### Use cases & Examples
```suggestion
### Use Cases & Examples
```

2024-12-30 21:36 UTC, sunilarjun commented on docs/08.integration/12.rancher_sso_rbac.md
> +* Global role to run runtime scans from NeuVector SSO session on all clusters managed by Rancher Manager except local cluster. Need to create cluster roles to propagate the global role to all downstr
```suggestion
* Global role to run runtime scans from NeuVector SSO session on all clusters are managed by Rancher Manager except the local cluster. Users need to create cluster roles to propagate the global role to all downstream clusters.
```

2024-12-30 21:36 UTC, sunilarjun commented on docs/08.integration/12.rancher_sso_rbac.md
> +  + Create a cluster role template with following parameters:
```suggestion
  + Create a cluster role template with the following parameters: 
```

2024-12-30 21:36 UTC, sunilarjun commented on docs/08.integration/12.rancher_sso_rbac.md
> +   + Create a global cluster role with following parameter to inherit the role to all downstream clusters:
```suggestion
   + Create a global cluster role with the following parameter to inherit the role to all downstream clusters:
```

2024-12-30 21:36 UTC, sunilarjun commented on docs/08.integration/12.rancher_sso_rbac.md
> +   + Create project role binding on all downstream clusters for the above user and project containing cattle-neuvector-system namespace.
```suggestion
   + Create a project role binding on all downstream clusters for the above user and project containing cattle-neuvector-system namespace.
```

2024-12-30 21:36 UTC, sunilarjun commented on docs/08.integration/12.rancher_sso_rbac.md
> +* Create FedAdmin user. Always remember that logging in as FedAdmin to a master cluster. If you are not on a federated domain, the roles will be downgraded to Reader or Admin.
```suggestion
* Create a FedAdmin user. Always remember to login in as a FedAdmin to a master cluster. If you are not on a federated domain, the roles will be downgraded to Reader or Admin.
```

2024-12-30 21:36 UTC, sunilarjun commented on docs/08.integration/12.rancher_sso_rbac.md
> +  + Create a global role with following parameters. Using a global role, this role is also accessible to the other downstream clusters:
```suggestion
  + Create a global role with the following parameters. By using a global role it is also accessible by the other downstream clusters:
```

2024-12-30 21:36 UTC, sunilarjun commented on docs/08.integration/12.rancher_sso_rbac.md
> +  + Create a standard user and select the global role created for this use case. The default form is always a Base or Standard user.
```suggestion
  + Create a Standard user and select the global role created for this use case. The default form is always a Base or Standard user.
```

2024-12-30 21:36 UTC, sunilarjun commented on docs/08.integration/12.rancher_sso_rbac.md
> +#### NOTE: To switch between FedAdmin and FedReader, just change the verbs from * to get. Get is just the read permission, i.e., FedReader in this use case.
```suggestion
:::note
To switch between FedAdmin and FedReader, just change the verbs from * to `get`. `get` is just the read permission, i.e., FedReader in this use case.
:::
```

2024-12-30 21:36 UTC, sunilarjun commented on docs/08.integration/12.rancher_sso_rbac.md
> +* Customers can use this documentation and parameters as a basis for creating the SSO/RBAC rules of their choice. The support team can be contacted to help with errors and specific use cases via the
```suggestion
* Users can use this documentation and parameters as a basis for creating the SSO/RBAC rules of their choice. The support team can be contacted to help with errors and specific use cases via the SCC.
```

2024-12-30 21:36 UTC, sunilarjun commented on docs/08.integration/12.rancher_sso_rbac.md
> +A user can do a read-only few tasks and modify a few tasks on a cluster.
```suggestion
A user can do a few read-only tasks and modify a few tasks on a cluster.
```

2025-01-02 15:17 UTC, brunoebernardi commented
Hi @sunilarjun, Thank you for reviewing the PR and including suggestions. I've made the suggested adjustments, and I would appreciate it if you could review and check for approval when possible.

2025-01-02 22:10 UTC, sunilarjun approved these changes
Thank you for addressing the feedback! Content is approved and merging in.

2025-01-02 22:10 UTC, merged